namespace Azoxia.Core.Generators
{
    using Microsoft.CodeAnalysis;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// Incremental source generator that discovers <see cref="Azoxia.Core.DependencyInjection.IServiceRegister"/> and
    /// <see cref="Azoxia.Core.Configuration.IConfig"/> implementations and emits a static registration helper for the compiling assembly.
    /// </summary>
    [Generator]
    public class DependencyInjectionGenerator :
        IIncrementalGenerator
    {
        #region Fields

        private const string CONFIG_TYPENAME = "Azoxia.Core.Configuration.IConfig";

        private const string GENERATED_CLASS_NAME = "GeneratedServiceRegistrar";

        private const string SERVICE_REGISTER_TYPENAME = "Azoxia.Core.DependencyInjection.IServiceRegister";

        private const string TABS = "    ";

        #endregion Fields

        #region Utils

        /// <summary>
        /// Enumerates all named types declared under <paramref name="root"/> (nested namespaces included).
        /// </summary>
        /// <param name="root">The namespace symbol to traverse.</param>
        /// <returns>Yielded named type symbols.</returns>
        private IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol root)
        {
            foreach (var namespaceOrTypeSymbol in root.GetMembers())
            {
                if (namespaceOrTypeSymbol is INamespaceSymbol @namespace)
                {
                    foreach (var nested in GetAllTypes(@namespace))
                    {
                        yield return nested;
                    }
                }
                else if (namespaceOrTypeSymbol is INamedTypeSymbol type)
                {
                    yield return type;
                }
            }
        }

        /// <summary>
        /// Builds the generated C# source text for service registration and config singleton wiring.
        /// </summary>
        /// <param name="compilation">The compilation being analyzed.</param>
        /// <param name="serviceRegisterTypes">Concrete <c>IServiceRegister</c> types.</param>
        /// <param name="configTypes">Concrete <c>IConfig</c> types.</param>
        /// <returns>The full generated file contents.</returns>
        private string GetSourceOutput(
            Compilation compilation,
            List<INamedTypeSymbol> serviceRegisterTypes,
            List<INamedTypeSymbol> configTypes)
        {
            string assemblyName = compilation.AssemblyName?
                .Replace(" ", string.Empty)
                ?? "Azoxia.Core.Generated";

            string _namespace = $"{assemblyName}.DependencyInjection";

            StringBuilder sb = new();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// ");
            sb.AppendLine();
            sb.AppendLine($"namespace {_namespace}");
            sb.AppendLine("{");

            sb.AppendLine($"{TABS}using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine($"{TABS}using Microsoft.Extensions.Configuration;");
            sb.AppendLine($"{TABS}using Azoxia.Core.Configuration;");
            sb.AppendLine();

            sb.AppendLine($"{TABS}/// <summary>");
            sb.AppendLine($"{TABS}/// Auto-generated registration helper for Azoxia Core: applies all discovered");
            sb.AppendLine($"{TABS}/// <c>Azoxia.Core.DependencyInjection.IServiceRegister</c> implementations and registers");
            sb.AppendLine($"{TABS}/// <c>Azoxia.Core.Configuration.IConfig</c> types as singletons for this assembly.");
            sb.AppendLine($"{TABS}/// </summary>");
            sb.AppendLine($"{TABS}public static class {GENERATED_CLASS_NAME}");
            sb.AppendLine($"{TABS}{{");

            sb.AppendLine($"{TABS}{TABS}#region Methods");
            sb.AppendLine();

            sb.AppendLine($"{TABS}{TABS}/// <summary>");
            sb.AppendLine($"{TABS}{TABS}/// Registers Azoxia Core application services and configuration bindings for the compiling assembly.");
            sb.AppendLine($"{TABS}{TABS}/// </summary>");
            sb.AppendLine($"{TABS}{TABS}/// <param name=\"services\">The application service collection.</param>");
            sb.AppendLine($"{TABS}{TABS}/// <param name=\"configuration\">The configuration root used to bind <c>IConfig</c> implementations.</param>");
            sb.AppendLine($"{TABS}{TABS}public static void AddAzoxiaCore(this IServiceCollection services, IConfiguration configuration)");
            sb.AppendLine($"{TABS}{TABS}{{");

            foreach (INamedTypeSymbol serviceRegisterType in serviceRegisterTypes)
            {
                string serviceRegisterTypeName = serviceRegisterType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"{TABS}{TABS}{TABS}new {serviceRegisterTypeName}().Register(services, configuration);");
            }

            sb.AppendLine();

            foreach (INamedTypeSymbol configType in configTypes)
            {
                string configTypeName = configType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"{TABS}{TABS}{TABS}services.AddSingleton(typeof({configTypeName}), Config.GetOrCreateConfig<{configTypeName}>(configuration));");
            }

            sb.AppendLine($"{TABS}{TABS}}}");

            sb.AppendLine();
            sb.AppendLine($"{TABS}{TABS}#endregion Methods");

            sb.AppendLine($"{TABS}}}");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// When core symbols resolve, scans the compilation and adds the generated registrar source file.
        /// </summary>
        /// <param name="context">The source production context.</param>
        /// <param name="compilation">The current compilation.</param>
        private void WriteSourceOutput(SourceProductionContext context, Compilation compilation)
        {
            INamedTypeSymbol serviceRegisterTypeSymbol = compilation
                .GetTypeByMetadataName(SERVICE_REGISTER_TYPENAME);

            INamedTypeSymbol configTypeSymbol = compilation
                .GetTypeByMetadataName(CONFIG_TYPENAME);

            if (serviceRegisterTypeSymbol is null || configTypeSymbol is null)
            {
                return;
            }

            IEnumerable<INamedTypeSymbol> allTypes = GetAllTypes(compilation.GlobalNamespace);

            List<INamedTypeSymbol> serviceRegisters = new();
            List<INamedTypeSymbol> configs = new();

            foreach (INamedTypeSymbol type in allTypes)
            {
                if (type.IsAbstract || type.TypeKind != TypeKind.Class)
                {
                    continue;
                }

                if (type.AllInterfaces.Contains(serviceRegisterTypeSymbol, SymbolEqualityComparer.Default))
                {
                    serviceRegisters.Add(type);
                }

                if (type.AllInterfaces.Contains(configTypeSymbol, SymbolEqualityComparer.Default))
                {
                    configs.Add(type);
                }
            }

            context.AddSource($"{GENERATED_CLASS_NAME}.g.cs", GetSourceOutput(compilation, serviceRegisters, configs));
        }

        #endregion Utils

        #region Methods

        /// <summary>
        /// Hooks compilation output: registers generated DI bootstrap source for the assembly under analysis.
        /// </summary>
        /// <param name="context">The generator initialization context.</param>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterSourceOutput(context.CompilationProvider, WriteSourceOutput);
        }

        #endregion Methods
    }
}
